var tableauQuestion = [
    {   question : "Jezeli jedziesz 90km/h, a zblizasz sie do terenu zabudowanego, musisz:",
        propositionA : "Przyspieszyc",
        propositionB : "Zachowac swoja predkosc, jesli nie jedziesz obok innych pojazdow",
        propositionC : "Zwolnic",
        propositionD : "Zachowac swoja predkosc, o ile jest to bezpieczne",
        reponse : "C"},

    {   question : "Jesli skrecasz w prawo na swiatlach, ale widzisz przejscie dla pieszych, co robisz:",
        propositionA : "Mijasz pieszego",
        propositionB : "Sprawdzasz, czy w poblizu nie ma innych pojazdow",
        propositionC : "Czekasz, az pieszy przejdzie na druga strone",
        propositionD : "Patrzysz na pieszego ale kontynuujesz jazde",
        reponse : "C"},

    {   question : "Bez wczesniejszego oznakowania, predkosc w terenie zabudowanym to: __ mph",
        propositionA : "50",
        propositionB : "60",
        propositionC : "80",
        propositionD : "30",
        reponse : "A"},

  {   question : "Przed każdą zmianą pasa musisz:",
        propositionA : "Sprawdzic lusterko",
        propositionB : "Sprawdzic swoje martwe punkty",
        propositionC : "Wlaczyc kierunkowskaz",
        propositionD : "Wszystkie wymienione",
        reponse : "D"},

  {   question : "Jaki poziom alkoholu we krwi jest klasyfikowany jako \"jazda pod wplywem\"?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "Kiedy mozesz kontynuowac jazde na światlach?",
        propositionA : "Gdy jest zielone",
        propositionB : "Kiedy nie ma nikogo na skrzyzowaniu",
        propositionC : "Gdy jesteś w strefie szkolnej",
        propositionD : "Kiedy jest zielone i / lub czerwone i skrecasz w prawo",
        reponse : "D"},

  {   question : "Pieszy nie ma pierwszenstwa do przejscia, co robisz?",
        propositionA : "Pozwalasz mu przejsc",
        propositionB : "Trobisz zeby poszedl na pasy",
        propositionC : "Machasz, aby zasygnalizowac żeby przeszedl",
        propositionD : "Kontynuujesz, poniewaz sygnalizacja swietlna jest zielona",
        reponse : "D"},

  {   question : "Co jest dozwolone, gdy mija sie inny pojazd",
        propositionA : "Podazaj za nim uwaznie, aby szybciej przejechac",
        propositionB : "Mijasz go nie zwracajac uwagi na nic",
        propositionC : "Jedziesz po przeciwnej stronie drogi, by minac pojazd",
        propositionD : "Przekraczasz limit predkosci, aby wyprzedzic",
        reponse : "C"},

  {   question : "Jedziesz autostrada, ktora wskazuje maksymalna predkosc 80mph. Wiekszość ruchu jedzie z predkoscia 90mph, wiec nie powinienes jechac szybciej niz:",
        propositionA : "50 mph",
        propositionB : "60 mph",
        propositionC : "90 mph",
        propositionD : "80 mph",
        reponse : "D"},

  {   question : "Kiedy jestes wyprzedzany przez inny pojazd, czego NIE nalezy robic:",
        propositionA : "Zwalniac",
        propositionB : "Sprawdzac lusterka",
        propositionC : "Patrzec na innych kierowcow",
        propositionD : "Zwiekszac predkosci",
        reponse : "D"},
]
