Citizen.CreateThread(function()
    while true do
    	Citizen.Wait(0)
    	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
    	roundx = tonumber(string.format("%.2f", x))
    	roundy = tonumber(string.format("%.2f", y))
    	roundz = tonumber(string.format("%.2f", z))
        SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~X:~s~ "..roundx)
		DrawText(0.33, 0.00)
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Y:~s~ "..roundy)
		DrawText(0.44, 0.00)
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Z:~s~ "..roundz)
		DrawText(0.55, 0.00)
		heading = GetEntityHeading(GetPlayerPed(-1))
		roundh = tonumber(string.format("%.2f", heading))
        SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Heading:~s~ "..roundh)
		DrawText(0.40, 0.05)
		speed = GetEntitySpeed(PlayerPedId())
		rounds = tonumber(string.format("%.2f", speed)) 
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Player Speed: ~s~"..rounds)
		health = GetEntityHealth(PlayerPedId())
		DrawText(0.40, 0.90)
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Player Health: ~s~"..health)
		DrawText(0.40, 0.85)
		veheng = GetVehicleEngineHealth(GetVehiclePedIsUsing(PlayerPedId()))
		vehbody = GetVehicleBodyHealth(GetVehiclePedIsUsing(PlayerPedId()))
		if IsPedInAnyVehicle(PlayerPedId(), 1) then
		vehenground = tonumber(string.format("%.2f", veheng))
		vehbodround = tonumber(string.format("%.2f", vehbody))
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Engine Health: ~s~"..vehenground)
		DrawText(0.0, 0.73)
		SetTextFont(0)
		SetTextProportional(1)
		SetTextScale(0.0, 0.70)
		SetTextDropshadow(1, 0, 0, 0, 255)
		SetTextEdge(1, 0, 0, 0, 255)
		SetTextDropShadow()
		SetTextOutline()
		SetTextEntry("STRING")
		AddTextComponentString("~r~Body Health: ~s~"..vehbodround)
		DrawText(0.0, 0.69) --hehe
	end
    end
end)
