Locales['en'] = {
	['ooc_help'] = 'Napisz wiadomosc poza postacia',
	['ooc_prefix'] = 'OOC | %s',
	['twt_help'] = 'Wyslij Tweeta',
	['twt_prefix'] = '^0[^4Twitter^0] (^5@%s^0)',
	['me_help'] = 'Akcja gracza',
	['me_prefix'] = 'me | %s',
	['do_help'] = 'Akcja gracza',
	['do_prefix'] = 'do | %s',
	['news_help'] = 'Oglos Wiadomosci',
	['news_prefix'] = 'Daily NEWS | %s',
	['ooc_argument_name'] = 'wiadomosc',
	['ooc_argument_help'] = 'wiadomosc',
	['ooc_unknown_command'] = '^1%s^0 nie jest prawidlowa komenda!',
}